version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: "oneplace"
      MYSQL_DATABASE: "oneplace"
      MYSQL_USER: "oneplace"
      MYSQL_PASSWORD: "oneplace"
    volumes:
      - ./server/data/docker/mysql:/var/lib/mysql
      - ./server/data/mysql:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    image: redis:4
    ports:
      - "6381:6379"
    volumes:
      - ./server/data/docker/redis:/data
