version: '3.1'
services:
  # golos-full:
  #   container_name: golos-full
  #   image: goloschain/golos
  #   volumes:
  #     - "/dev/shm:/shm"
  #     - "./server/data/docker/golos:/var/lib/golosd"
  #     - "./server/data/docker/golos.config.ini:/etc/golosd/config.ini"
  #   ports:
  #     - "2001:2001"
  #     - "8090:8090"
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: "oneplace"
      MYSQL_DATABASE: "oneplace"
      MYSQL_USER: "oneplace"
      MYSQL_PASSWORD: "oneplace"
    volumes:
      - ./server/data/docker/mysql:/var/lib/mysql
      - ./server/data/mysql:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    image: redis:4
    ports:
      - "6381:6379"
    volumes:
      - ./server/data/docker/redis:/data
